// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYd8--mfLCjQMSFwrIINp-mLNQZjwHpic',
    appId: '1:870428658400:web:bf43292a4aa4b094705e85',
    messagingSenderId: '870428658400',
    projectId: 'my-wedding-402918',
    authDomain: 'my-wedding-402918.firebaseapp.com',
    databaseURL: 'https://my-wedding-402918-default-rtdb.firebaseio.com',
    storageBucket: 'my-wedding-402918.firebasestorage.app',
    measurementId: 'G-NLCHWGMY06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqgPEFboRcyhYG5WG6hpLL8zzLHFUX_8',
    appId: '1:870428658400:android:91b2558ae90d217d705e85',
    messagingSenderId: '870428658400',
    projectId: 'my-wedding-402918',
    databaseURL: 'https://my-wedding-402918-default-rtdb.firebaseio.com',
    storageBucket: 'my-wedding-402918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmgi1HgbrI2AxEknvNmk-pgKBxmq1EKw',
    appId: '1:870428658400:ios:f27a5f87367b1e14705e85',
    messagingSenderId: '870428658400',
    projectId: 'my-wedding-402918',
    databaseURL: 'https://my-wedding-402918-default-rtdb.firebaseio.com',
    storageBucket: 'my-wedding-402918.firebasestorage.app',
    iosBundleId: 'com.example.myWedding',
  );
}
